image: /home/hugo/aidguide_04/aidguide_04_ws/src/aidguide_04_my_nav2_system/config/aidguide_04_map.pgm
mode: trinary
resolution: 0.05
origin: [-8.16, -8.97, 0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.25